# Generated by Django 5.1.2 on 2025-01-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_alias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("verified", "Can automatically create verified events")
                ]
            },
        ),
    ]
