# Generated by Django 5.1.2 on 2024-10-30 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("organizer_alias", models.CharField(max_length=100)),
                ("is_virtual", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("competition", "Zawody"),
                            ("workshop", "Warsztaty"),
                            ("conference", "Konferencja"),
                            ("show", "Show"),
                            ("festival", "Festiwal"),
                            ("convention", "Konwent"),
                            ("other", "Inne"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_aerial", models.BooleanField(default=True)),
                ("main_link", models.URLField()),
                ("additional_links", models.JSONField(blank=True, default=list)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
