# Generated by Django 5.1.2 on 2024-12-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_yearlycalendar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="additional_links",
        ),
        migrations.AddField(
            model_name="event",
            name="additional_label_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="additional_label_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="additional_url_1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="additional_url_2",
            field=models.URLField(blank=True, null=True),
        ),
    ]
