# Generated by Django 5.1.2 on 2025-01-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0007_delete_yearlycalendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="additional_url_1",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="additional_url_2",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="main_link",
            field=models.URLField(max_length=300),
        ),
    ]
