# Generated by Django 5.1.2 on 2025-03-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendar_app",
            "0008_event_is_verified_alter_event_additional_url_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("competition", "competition"),
                    ("workshop", "workshop"),
                    ("conference", "conference"),
                    ("show", "show"),
                    ("festival", "festival"),
                    ("convention", "convention"),
                    ("camp_intensive", "camp/intensive"),
                    ("other", "other"),
                ],
                max_length=20,
            ),
        ),
    ]
